[package]
name = "dqg"
version = "0.1.0"
authors = ["Florian Sextl <sextl@in.tum.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nauty-Traces-sys = {git = "https://github.com/firefighterduck/nauty-Traces-sys"}
kissat-rs = {git = "https://github.com/firefighterduck/kissat-rs", branch = "main" }
libffi = "1.0.0"
custom_debug_derive = "0.5.0"
itertools = "0.10.0"
nom = "6.1.2"
thiserror = "1.0.24"
